services:
  - type: web
    name: portfolio
    env: python
    root: .
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    publishDirectory: ""
    envVars:
      - key: FLASK_CONFIG
        value: ProductionConfig
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATABASE_URL
        value: postgresql+psycopg://portfolios_db_user:fo914A2nEFucRJH6PVNb0mISCtWmmGpH@dpg-d826vm3bc2fs73c3isn0-a.oregon-postgres.render.com/portfolios_db
