services:
  - type: web
    name: portfolio
    env: python
    root: .
    plan: free
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: gunicorn index:app
    publishDirectory: ""
    envVars:
      - key: FLASK_CONFIG
        value: ProductionConfig
      - key: PYTHONUNBUFFERED
        value: "true"
