services:
  - type: web
    name: portfolio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn index:app
    envVars:
      - key: FLASK_CONFIG
        value: ProductionConfig
      - key: PYTHONUNBUFFERED
        value: "true"
